### ISSUE TITLE
[Feature]: 需要一个删除维度接口

### ISSUE THREAD

**Issue by banchen19** [LiteLDev/MoreDimensions#2]
### Is your feature request related to a problem? Please describe.

插件卸载以后，存档内尚未被删除的维度数据仍然存在，可不可以实现删除？

### Describe the solution you'd like

添加一个删除维度的接口

**Comment by quizhizhe** [comment]
这样设计不好，存档内删除维度数据会遍历存档内所有的数据，存档层上的修改还是交给存档编辑软件（虽然目前没有任何支持多维度的BE存档编辑软件），故不提供存档删除维度数据接口
