### ISSUE TITLE
Add How to Usage Plugin 

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/MoreDimensions#4]
I'm trying to use a plugin. But I don't understand how to use New Dimension.

**Comment by quizhizhe** [comment]
> I'm trying to use a plugin. But I don't understand how to use New Dimension.

https://github.com/LiteLDev/MoreDimensions/wiki/FlatGeneratedVillages

But all is Chinese

**Comment by quizhizhe** [comment]
In the future, I will gradually create tutorials with examples

**Comment by ShrBox** [comment]
I have translate the wiki to English
